name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
      - 'feature-**'


  pull_request:
    branches:
      - master
      - develop


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B verify

