name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
      - 'feature-**'


  pull_request:
    branches:
      - master
      - develop


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn -B verify

      - name: Jacoco report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: jacoco-covera-report
          path: target/site/jacoco/


